-- poly_all PostgreSQL schema

-- All market snapshots (for backtesting and analysis)
CREATE TABLE IF NOT EXISTS market_snapshots (
    id              BIGSERIAL PRIMARY KEY,
    captured_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    market_id       TEXT NOT NULL,
    condition_id    TEXT NOT NULL,
    question        TEXT,
    market_type     TEXT,           -- price_prediction | event_outcome | unknown
    end_time        TIMESTAMPTZ,
    liquidity       NUMERIC,
    volume_24h      NUMERIC,
    yes_price       NUMERIC,
    no_price        NUMERIC,
    spread          NUMERIC,
    extra           JSONB           -- model-specific fields (current_price, target, etc.)
);

CREATE INDEX ON market_snapshots (condition_id, captured_at DESC);
CREATE INDEX ON market_snapshots (market_type, captured_at DESC);

-- All signals generated by the detector
CREATE TABLE IF NOT EXISTS signals (
    id              BIGSERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    market_id       TEXT NOT NULL,
    direction       TEXT NOT NULL,  -- YES | NO
    market_price    NUMERIC,
    model_prob      NUMERIC,
    edge            NUMERIC,
    market_type     TEXT,
    acted_on        BOOLEAN DEFAULT FALSE
);

-- All trades executed
CREATE TABLE IF NOT EXISTS trades (
    id              BIGSERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    market_id       TEXT NOT NULL,
    direction       TEXT NOT NULL,
    bet_amount      NUMERIC,
    actual_amount   NUMERIC,
    actual_price    NUMERIC,
    order_id        TEXT,
    dry_run         BOOLEAN DEFAULT TRUE,
    edge            NUMERIC,
    outcome         TEXT,           -- WIN | LOSS | PENDING | NULL
    pnl             NUMERIC,
    resolved_at     TIMESTAMPTZ
);

CREATE INDEX ON trades (market_id);
CREATE INDEX ON trades (outcome);
